[mongodb]
mongodb-dev.sowjanya.fun

[catalogue]
catalogue-dev.sowjanya.fun

[redis]
redis-dev.sowjanya.fun

[user]
user-dev.sowjanya.fun

[cart]
cart-dev.sowjanya.fun

[mysql]
mysql-dev.sowjanya.fun

[shipping]
shipping-dev.sowjanya.fun

[payment]
payment-dev.sowjanya.fun

[rabbitmq]
rabbtmq-dev.sowjanya.fun

[frontend]
roboshop-dev.sowjanya.fun

[all:vars]
ansible_user=ec2-user
ansible_password=DevOps321
mongodb_host=mongodb-dev.sowjanya.fun
catalogue_host=catalogue-dev.sowjanya.fun
redis_host=redis-dev.sowjanya.fun
cart_host=cart-dev.sowjanya.fun
user_host=user-dev.sowjanya.fun
mysql_host=mysql-dev.sowjanya.fun
shipping_host=shipping-dev.sowjanya.fun
rabbtimq_host=rabbitmq-dev.sowjanya.fun
payment_host=payment-dev.sowjanya.fun
frontend_host=roboshop-dev.sowjanya.fun